matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          language: cpp
          compiler:
              - clang
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  sources:
                      - sourceline: 'ppa:beineri/opt-qt594-trusty'
                  packages:
                      - libc++-dev
                      - libc++abi-dev
                      - libmount-dev
                      - qt59qbs

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             brew update &> /dev/null
          && travis_wait brew install --force-bottle conan gettext qbs
          && conan config install https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install https://vuo.org/sites/default/files/conan-linux.zip
          && . /opt/qt59/bin/qt59-env.sh
      ; fi

install:
    - qbs --version
    - qbs setup-qt --detect
    - qbs setup-toolchains --detect
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             qbs config defaultProfile clang
      ; fi
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --confirm glib/*
    - cat /Users/travis/.conan/data/glib/2.51.1-4/vuo/stable/build/05e73570a1c6a8d339eda6b548143010444972b8/_build/config.log
